etitle: Ben Uehlinger
logo: /assets/img/head shot.jpeg
description: Aspiring Data Scientist | Modeling & Analytics at KPMG LLP  
description: (571) 271-2018 • [benuehlinger@gmail.com](mailto:benuehlinger@gmail.com) • Leesburg, VA / McLean, VA
show_downloads: true
theme: jekyll-theme-minimal
