title: Shaw Talebi
#logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal





# etitle: Ben Uehlinger
# logo: /assets/img/head shot.jpeg
# description: Aspiring Data Scientist | Modeling & Analytics at KPMG LLP  
# show_downloads: true
# theme: jekyll-theme-minimal
